#:import HeartfeltHellosButton app.widgets.heartfelt_hellos_button

ShowcaseScreen:
    name: 'Title_Screen'
    display_name: "Heartfelt Hellos"
    
    Label:
        text: "Let's Reconnect!"
        font_size:60
        color: 0, 0, 0

    Label:
        text: "What type conversation ideas do you want?" 
        font_size:40
        halign:"center"
        text_size: cm(8), cm(7)
        color: 0, 0, 0
